const CONFIG = {
    GRID_COLS: 20, GRID_ROWS: 12, CELL_SIZE: 50,
    CANVAS_WIDTH: 1000, CANVAS_HEIGHT: 600,
    START_GOLD: 170, START_LIVES: 500, LEGACY_START_LIVES: 25, BASE_HP_PER_LEGACY_LIFE: 20, TOTAL_WAVES: 20,
    PROJECTILE_SPEED: 420, SELL_RATIO: 0.5,
    WAVE_TIMER: 25, FIRST_WAVE_TIMER: 18,
    WAVE_REWARD_BASE: 30, WAVE_REWARD_PER_WAVE: 6,
    SKIP_BONUS_BASE: 15, SKIP_BONUS_PER_WAVE: 5,
    COOP_MONEY_MULTIPLIER: 1.05,
    COOP_START_GOLD_MULTIPLIER: 1.1,
    COOP_HP_MULTIPLIER: 1.48,
    COOP_COUNT_MULTIPLIER: 0.92,
    COOP_INTERVAL_MULTIPLIER: 1.08,
    MAX_FARMS: 5,
};

const DIFFICULTY_LEVELS = {
    easy: {
        id: 'easy',
        name: 'Easy',
        badge: 'Лёгкий вход',
        description: 'Меньше врагов, медленнее темп, слабее боссы. Подходит для спокойного изучения карт и башен.',
        startGold: 272,
        countScale: 0.65,
        intervalScale: 1.18,
        enemyHpScale: 0.78,
        enemySpeedScale: 0.90,
        bossHpScale: 0.68,
        bossSpeedScale: 0.86,
        bossDamageScale: 0.72,
        rewardScale: 1.10,
    },
    medium: {
        id: 'medium',
        name: 'Medium',
        badge: 'Сбалансировано',
        description: 'Умеренный темп и чуть мягче волны. Ошибки всё ещё опасны, но игра даёт больше пространства.',
        startGold: 213,
        countScale: 0.84,
        intervalScale: 1.08,
        enemyHpScale: 0.90,
        enemySpeedScale: 0.95,
        bossHpScale: 0.84,
        bossSpeedScale: 0.94,
        bossDamageScale: 0.88,
        rewardScale: 1.04,
    },
    hard: {
        id: 'hard',
        name: 'Hard',
        badge: 'Оригинальный режим',
        description: 'Текущий полный баланс: максимальный темп, плотные волны и самые жёсткие боссы.',
        startGold: CONFIG.START_GOLD,
        countScale: 1,
        intervalScale: 1,
        enemyHpScale: 1,
        enemySpeedScale: 1,
        bossHpScale: 1,
        bossSpeedScale: 1,
        bossDamageScale: 1,
        rewardScale: 1,
    },
};

const DEFAULT_DIFFICULTY_ID = 'hard';

const ABILITY_TYPES = {
    fortress: {
        name: 'Бастион',
        icon: '🛡',
        short: 'ЩИТ',
        unlockTime: 60,
        recharge: 60,
        target: 'tower',
        duration: 18,
        fireRateMultiplier: 1.5,
        description: 'Делает турель неуязвимой и ускоряет её стрельбу на 50% на короткое время.',
    },
    freeze: {
        name: 'Крио-Стоп',
        icon: '❄',
        short: 'СТАН',
        unlockTime: 120,
        recharge: 120,
        target: 'point',
        radius: 88,
        damage: 55,
        stunDuration: 4,
        description: 'Бьёт по кругу, немного дамажит и полностью останавливает мобов на 4 секунды.',
    },
    sunfall: {
        name: 'Солнечный Выжигатель',
        icon: '☀',
        short: 'ЛУЧ',
        unlockTime: 180,
        recharge: 180,
        target: 'point',
        radius: 148,
        centerRadius: 58,
        damage: 320,
